### ISSUE TITLE
Data availabiltiy

### ISSUE THREAD

**Issue by thak123** [tkuculo/QuoteKG#1]
Hi @t-kuculo, @sgottsch  

Is the preprocessed data available somewhere?

**Comment by t-kuculo** [comment]
Hi @thak123. Yes, we have made the data publicly available on Zenodo. You can find the interface to QuoteKG and the link to the  .ttl file by following the QuoteKG link in the repository Readme. This is the Zenodo link where you can download the data: 

https://zenodo.org/record/5770516
